In [3]:
import numpy as np
np.__version__

'1.26.4'

In [13]:
# Defining an array and the type 
arr1= np.array([1,3,24,35])
type(arr1)

numpy.ndarray

In [11]:
# Address of the array
id(arr1)

3036396607440

In [19]:
# copy of the value of different array but the address id remains different 

arr2= np.array([2,34,23,21])
arr1 = np.copy(arr2)
arr1

array([ 2, 34, 23, 21])

In [23]:
id(arr1)

3036396607632

In [25]:
id(arr2)

3036396607440

In [27]:
np.array({1,3,4,5,22,12})

array({1, 3, 4, 5, 22, 12}, dtype=object)

In [31]:
len10 = np.arange(10)
len(len10)

10

In [35]:
arr3 = np.array([12,2.34,'Hi'])
arr3

array(['12', '2.34', 'Hi'], dtype='<U32')

In [37]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
arr3.ndim


1

In [51]:
data = np.random.randn(100,100)
np.mean(data)
data

array([[-1.47535751, -0.22183823, -1.38783103, ..., -1.16909738,
         0.53697817,  1.16661687],
       [ 0.05255576, -0.46496082, -0.93915297, ...,  0.32355352,
        -1.80497502,  0.5261315 ],
       [ 0.5660776 ,  0.75407642, -0.83946673, ...,  0.87230811,
         1.41026861, -0.27504951],
       ...,
       [-1.29398616, -0.69535523,  2.29631958, ...,  1.60924116,
         0.27665604,  0.68906791],
       [ 1.59476071,  1.00248224, -0.07419211, ..., -0.06980437,
        -1.13292773, -0.15416904],
       [-0.25189525, -0.78338008,  0.20319965, ..., -1.08713141,
         0.70150376, -1.38237945]])

In [55]:
# Matrix Operations

A = np.array([[1,2,3],[2,6,7],[5,5,8]])
B = np.array([[2,4,5],[1,2,4],[9,7,6]])


In [57]:
np.dot(A,B)

array([[31, 29, 31],
       [73, 69, 76],
       [87, 86, 93]])

In [59]:
np.transpose(A)

array([[1, 2, 5],
       [2, 6, 5],
       [3, 7, 8]])

In [63]:
np.linalg.inv(A)

array([[-1.44444444,  0.11111111,  0.44444444],
       [-2.11111111,  0.77777778,  0.11111111],
       [ 2.22222222, -0.55555556, -0.22222222]])

In [65]:
np.linalg.det(A)

-8.999999999999998

In [69]:
B.swapaxes(0,1)

array([[2, 1, 9],
       [4, 2, 7],
       [5, 4, 6]])