In [7]:
# Generate a matrix of 6 by 4 with values in the range 10 to 20. Display the value at location (4,3) also display the size of the matrix

import numpy as np
matrix = np.random.randint(10,20,size=(6,4))
value = matrix[4,3]
print(matrix)
print(value)
print(matrix.size)



[[16 16 13 17]
 [17 16 16 17]
 [14 14 17 14]
 [16 19 17 19]
 [11 14 16 12]
 [10 17 13 14]]
12
24


In [9]:
# Create a matrix A of size 4 by 6 with random value in the range 0 to 1. Obtain the transpose of the matrix. Display the dimension before and after


import numpy as np
A = np.random.randint(0,1, size=(4,6))
print(A)
print(A.shape)
A_transpose = A.T
print(A_transpose)
print(A_transpose.shape)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(4, 6)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(6, 4)


In [23]:
# Write a program to create a matrix of size 5 by 5 square matrix, diagonal matrix, symmetric and unit matrix

import numpy as np
square_matrix = np.random.randint(5,10,size=(5,5))
print(square_matrix)

diagonal_matrix = np.diag(np.random.randint(5,10,size=5))
print(diagonal_matrix)

random_matrix=np.random.randint(5,10, size= (5,5))
random_matrix_transpose= random_matrix.T
symmetric_matrix = random_matrix + random_matrix_transpose
print(symmetric_matrix)

unit_matrix= np.eye(5,dtype=int)
print(unit_matrix)

[[5 6 9 9 7]
 [9 6 9 7 6]
 [7 6 5 7 9]
 [5 7 6 6 8]
 [9 7 8 9 9]]
[[7 0 0 0 0]
 [0 7 0 0 0]
 [0 0 6 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]
[[14 10 12 13 14]
 [10 18 14 13 13]
 [12 14 12 14 15]
 [13 13 14 12 14]
 [14 13 15 14 10]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [35]:
#Find A+B, A-1/2B, and 5A when the matrices A,B are as follows: A = [(1,-4),(-4,1)], B = [(1,-8),(-8,2)]

import numpy as np
A = np.array([[1,-4],[-4,1]])
B = np.array([[1,-8],[-8,2]])
print("A+B: ",A+B)
print("A-1/2B: ", A-1/2*B)
print("5A : ",5*A)

A+B:  [[  2 -12]
 [-12   3]]
A-1/2B:  [[0.5 0. ]
 [0.  0. ]]
5A :  [[  5 -20]
 [-20   5]]


In [37]:
# Find AB and BA when matrices A,B are as follows respectively: AB =[[2,3,1],[4,5,1]], B = [[-1,2],[4,-2],[3,6]]

import numpy as np
A= np.array([[2,3,1],[4,5,1]])
B= np.array([[-1,2],[4,-2],[3,6]])
print(" AB : ", np.dot(A,B))
print("BA : ",np.dot(B,A))

 AB :  [[13  4]
 [19  4]]
BA :  [[ 6  7  1]
 [ 0  2  2]
 [30 39  9]]


In [43]:
# Find the Reverse Matrix A,B when the 2 by 2 matrix A,B are as follows respectively: A=[[1,3],[5,7]],B=[[4,-6],[-8,12]]

import numpy as np
A= np.array([[1,5],[5,7]])
B = np.array([[4,-6],[-8,12]])
detA= np.linalg.det(A)
Ainv= np.linalg.inv(A)
detB = np.linalg.det(B)
print(detA)
print(Ainv)
print(detB)

-17.999999999999996
[[-0.38888889  0.27777778]
 [ 0.27777778 -0.05555556]]
0.0


In [47]:
''' You are given a set of 2D points corresponding the vertices of a geometric shape
1. Create a numpy array P of shape(N,2) contaning atleast 6 dimensional points of your choice 
2.Define
        A rotation matrix for a rotation of 45degree
        A scaling matrix that scales the x-axis by 2 and the y-axis by 0.5
3. Combine the rotation and scaling into a single linear transformation matrix
4. Apply the combined transformation to all points using numpy matrix operations(no loops).
5. Compute and print:
            The transformed coordinates
            The Eucledian distance between each original point and its transformed point'''

import numpy as np
P = np.array([
    [1, 2],
    [3, 5],
    [6, 4],
    [8, 7],
    [5, 9],
    [2, 6]
])

print("Original Points (P):\n", P)

theta = 45  # degrees
theta_rad = np.deg2rad(theta)

R = np.array([
    [np.cos(theta_rad), -np.sin(theta_rad)],
    [np.sin(theta_rad),  np.cos(theta_rad)]
])

S = np.array([
    [2, 0],
    [0, 0.5]
])

T = R @ S

print("\nCombined Transformation Matrix:\n", T)

P_transformed = P @ T.T  

print("\nTransformed Coordinates:\n", P_transformed)

# Compute Euclidean distance between original and transformed points
distances = np.linalg.norm(P_transformed - P, axis=1)

print("\nEuclidean Distance for each point:\n", distances)


[[1 2]
 [2 3]
 [3 4]
 [5 6]
 [3 7]
 [8 9]]
(6, 2)


In [61]:
''' 2.Consider the following real symmetric matrix A:
A=[[4,1,1],
    [1,3,0],
    [1,0,2]]
Tasks:
1. Represent the matrix A using Numpy
2. Compute the eigen values and eigen vectors of A.
3. Verify nummerically that A v = lamda v for one eigenvalue-eigenvector pair.
4. Check whether the eignevectors are orthogonal.
5. Sort the eigenvalues in descending order and rearrange eigenvectors accordingly.
'''
import numpy as np

A = np.array([[4,1,1],
              [1,3,0],
              [1,0,2]])

eigenvalues,eigenvectors = np.linalg.eigh(A)

print(eigenvalues)
print(eigenvectors)

v = eigenvectors[:,0]
lam = eigenvalues[0]

left = A@v
right = lam*v

print(left)
print(right)

orthogonality_check = eigenvectors.T @ eigenvectors
print(orthogonality_check)

idx= np.argsort(eigenvalues)[::-1]
eigenvalues_sorted = eigenvalues[idx]
eigenvectors_sorted = eigenvectors[:,idx]

print(eigenvalues_sorted)
print(eigenvectors_sorted)

[1.46791111 2.65270364 4.87938524]
[[-0.44909879  0.29312841 -0.84402963]
 [ 0.29312841 -0.84402963 -0.44909879]
 [ 0.84402963  0.44909879 -0.29312841]]
[-0.6592371   0.43028646  1.23896047]
[-0.6592371   0.43028646  1.23896047]
[[ 1.00000000e+00  2.34664261e-16  2.76630980e-16]
 [ 2.34664261e-16  1.00000000e+00 -2.79056110e-16]
 [ 2.76630980e-16 -2.79056110e-16  1.00000000e+00]]
[1.46791111 2.65270364 4.87938524]
[[-0.44909879  0.29312841 -0.84402963]
 [ 0.29312841 -0.84402963 -0.44909879]
 [ 0.84402963  0.44909879 -0.29312841]]


In [ ]:
'''