In [3]:
# Write a program using numpy to create a zero vector of size 5 and display it

import numpy as np
zero_vector = np.zeros(5)
print("Zero Vector of size 5:", zero_vector)

Zero Vector of size 5: [0. 0. 0. 0. 0.]


In [5]:
# Write a program using numpy to create a zero vector of size n(user defined) and display it

import numpy as np
n = int(input("Enter the size of the zero vector: "))
zero_vector = np.zeros(n)
print("Zero Vector of size", n, ":", zero_vector)


Enter the size of the zero vector:  5


Zero Vector of size 5 : [0. 0. 0. 0. 0.]


In [7]:
# Create a one vector of size 7 using numpy. Print the vector and shape

import numpy as np
one_vector = np.ones(7)
print(one_vector)
print(one_vector.shape)

[1. 1. 1. 1. 1. 1. 1.]
(7,)


In [9]:
#Create a one vector of length 10,reshape it into a 2 by 5 matrix and compute the row-wise and column-wise sums

import numpy as np

one_vector = np.ones(10)
matrix = one_vector.reshape(2,5)

row_sums = np.sum(matrix,axis=1)
print(row_sums)
column_sums = np.sum(matrix,axis=0)
print(column_sums)

[5. 5.]
[2. 2. 2. 2. 2.]


In [11]:
# Write a program to create zero matrix of size 3 by 3 using numpy

import numpy as np
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Generate a square matrix of size n by n with random integers

import numpy as np
n = int(input("Enter a number: "))
random_matrix = np.random.randint(0,10,size=(n,n))
print(random_matrix)

Enter a number:  7


[[4 0 3 8 9 8 5]
 [8 7 6 6 6 8 2]
 [6 3 9 7 0 3 6]
 [8 4 3 6 8 4 7]
 [3 5 0 9 3 5 8]
 [8 8 0 6 9 5 6]
 [9 9 8 0 4 9 7]]


In [17]:
""" The prices of three grocery items rice, milk and bread are 120rs,45rs and 30rs per item respectively. A customer wants to buy 3 packets of rice,4 bottles of milk and 5 loaves of bread 
1. Represent the item prices and quantities purchased as numpy vectors p and q respectively
2. Using appropriate numpy vector operations, compute the total cost of the purchase
"""
import numpy as np
p = np.array([120,45,30])
q = np.array([3,4,5])

total_cost = np.dot(p,q)
print("Prices vector: ",p)
print("Quantity vector: ",q)
print("Total cost: ",total_cost)

Prices vector:  [120  45  30]
Quantity vector:  [3 4 5]
Total cost:  690
